services:
 surya_finetuning:
   build: 
     context: .
     dockerfile: Dockerfile
   volumes:
     - .:/app
     - ../dataset:/dataset
   environment:
     - PYTHONUNBUFFERED=1
   deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: 1
             capabilities: [gpu]
   command: tail -f /dev/null